name: mobile_driver
description: Driver app for Taxi (Flutter)
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  uuid: ^4.4.2
  sse_client: ^0.0.10
  geolocator: ^12.0.0
  google_maps_flutter: ^2.7.0
  flutter_background_service: ^5.0.5
  # optional local notifications (for foreground beeps)
  flutter_local_notifications: ^17.2.3
  firebase_messaging: ^14.8.1
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
