name: mobile_rider
description: Minimal Flutter sample using Taxi API SDK
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  http: ^1.2.2
  taxi_openapi:
    path: ../backend/docs/dart-sdk
  shared_preferences: ^2.3.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^11.1.0
  firebase_messaging: ^14.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
